//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UHFDemo {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WinFormString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinFormString() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UHFDemo.WinFormString", typeof(WinFormString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 天线 的本地化字符串。
        /// </summary>
        internal static string Antenna {
            get {
                return ResourceManager.GetString("Antenna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接读写器 的本地化字符串。
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CRC 的本地化字符串。
        /// </summary>
        internal static string CRC {
            get {
                return ResourceManager.GetString("CRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据区 的本地化字符串。
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据长度 的本地化字符串。
        /// </summary>
        internal static string DataLen {
            get {
                return ResourceManager.GetString("DataLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 192.168.0.178 的本地化字符串。
        /// </summary>
        internal static string DefaultIP {
            get {
                return ResourceManager.GetString("DefaultIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4001 的本地化字符串。
        /// </summary>
        internal static string DefaultPort {
            get {
                return ResourceManager.GetString("DefaultPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UHF RFID Reader Demo v 的本地化字符串。
        /// </summary>
        internal static string DemoName {
            get {
                return ResourceManager.GetString("DemoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停用 的本地化字符串。
        /// </summary>
        internal static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 断开连接 的本地化字符串。
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EPC 的本地化字符串。
        /// </summary>
        internal static string EPC {
            get {
                return ResourceManager.GetString("EPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 载波频率(MHz) 的本地化字符串。
        /// </summary>
        internal static string Freq {
            get {
                return ResourceManager.GetString("Freq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取并清空缓存 的本地化字符串。
        /// </summary>
        internal static string GetAndClearBuffer {
            get {
                return ResourceManager.GetString("GetAndClearBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取缓存 的本地化字符串。
        /// </summary>
        internal static string GetBuffer {
            get {
                return ResourceManager.GetString("GetBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在获取缓存 的本地化字符串。
        /// </summary>
        internal static string GettingBuffer {
            get {
                return ResourceManager.GetString("GettingBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在盘存 的本地化字符串。
        /// </summary>
        internal static string Inventorying {
            get {
                return ResourceManager.GetString("Inventorying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        internal static string ncDescription {
            get {
                return ResourceManager.GetString("ncDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP地址 的本地化字符串。
        /// </summary>
        internal static string ncIp {
            get {
                return ResourceManager.GetString("ncIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mac地址 的本地化字符串。
        /// </summary>
        internal static string ncMac {
            get {
                return ResourceManager.GetString("ncMac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子网掩码 的本地化字符串。
        /// </summary>
        internal static string ncMask {
            get {
                return ResourceManager.GetString("ncMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择网卡 的本地化字符串。
        /// </summary>
        internal static string nNoNetCardSelect {
            get {
                return ResourceManager.GetString("nNoNetCardSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 芯片版本 的本地化字符串。
        /// </summary>
        internal static string npChipVer {
            get {
                return ResourceManager.GetString("npChipVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复默认 的本地化字符串。
        /// </summary>
        internal static string npDefault {
            get {
                return ResourceManager.GetString("npDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备IP 的本地化字符串。
        /// </summary>
        internal static string npDeviceIp {
            get {
                return ResourceManager.GetString("npDeviceIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备Mac地址 的本地化字符串。
        /// </summary>
        internal static string npDeviceMac {
            get {
                return ResourceManager.GetString("npDeviceMac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备名称 的本地化字符串。
        /// </summary>
        internal static string npDeviceName {
            get {
                return ResourceManager.GetString("npDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取配置 的本地化字符串。
        /// </summary>
        internal static string npGet {
            get {
                return ResourceManager.GetString("npGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主机Mac地址 的本地化字符串。
        /// </summary>
        internal static string npPcMac {
            get {
                return ResourceManager.GetString("npPcMac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复出厂 的本地化字符串。
        /// </summary>
        internal static string npReset {
            get {
                return ResourceManager.GetString("npReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重试 的本地化字符串。
        /// </summary>
        internal static string npRetry {
            get {
                return ResourceManager.GetString("npRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存配置 的本地化字符串。
        /// </summary>
        internal static string npSave {
            get {
                return ResourceManager.GetString("npSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在搜索设备 的本地化字符串。
        /// </summary>
        internal static string npSearchingNetPort {
            get {
                return ResourceManager.GetString("npSearchingNetPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索设备 的本地化字符串。
        /// </summary>
        internal static string npSearchNetPort {
            get {
                return ResourceManager.GetString("npSearchNetPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功次数 的本地化字符串。
        /// </summary>
        internal static string opSuccessCount {
            get {
                return ResourceManager.GetString("opSuccessCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PC 的本地化字符串。
        /// </summary>
        internal static string PC {
            get {
                return ResourceManager.GetString("PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个/秒 的本地化字符串。
        /// </summary>
        internal static string PerSec {
            get {
                return ResourceManager.GetString("PerSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相位 的本地化字符串。
        /// </summary>
        internal static string Phase {
            get {
                return ResourceManager.GetString("Phase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取次数 的本地化字符串。
        /// </summary>
        internal static string ReadCount {
            get {
                return ResourceManager.GetString("ReadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读标签 的本地化字符串。
        /// </summary>
        internal static string ReadTag {
            get {
                return ResourceManager.GetString("ReadTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rssi(dBm) 的本地化字符串。
        /// </summary>
        internal static string Rssi {
            get {
                return ResourceManager.GetString("Rssi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秒 的本地化字符串。
        /// </summary>
        internal static string Sec {
            get {
                return ResourceManager.GetString("Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始 的本地化字符串。
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始盘存 的本地化字符串。
        /// </summary>
        internal static string StartInventory {
            get {
                return ResourceManager.GetString("StartInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止盘存 的本地化字符串。
        /// </summary>
        internal static string StopInventory {
            get {
                return ResourceManager.GetString("StopInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在停止 的本地化字符串。
        /// </summary>
        internal static string Stopping {
            get {
                return ResourceManager.GetString("Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过滤行为 的本地化字符串。
        /// </summary>
        internal static string tagmask_Action {
            get {
                return ResourceManager.GetString("tagmask_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过滤长度(Hex bit) 的本地化字符串。
        /// </summary>
        internal static string tagmask_MaskLen {
            get {
                return ResourceManager.GetString("tagmask_MaskLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过滤ID 的本地化字符串。
        /// </summary>
        internal static string tagmask_MaskNo {
            get {
                return ResourceManager.GetString("tagmask_MaskNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过滤值 的本地化字符串。
        /// </summary>
        internal static string tagmask_MaskValue {
            get {
                return ResourceManager.GetString("tagmask_MaskValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过滤区域 的本地化字符串。
        /// </summary>
        internal static string tagmask_MemBank {
            get {
                return ResourceManager.GetString("tagmask_MemBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Session ID 的本地化字符串。
        /// </summary>
        internal static string tagmask_SessionID {
            get {
                return ResourceManager.GetString("tagmask_SessionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起始地址(Hex bit) 的本地化字符串。
        /// </summary>
        internal static string tagmask_StartAddr {
            get {
                return ResourceManager.GetString("tagmask_StartAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Truncate 的本地化字符串。
        /// </summary>
        internal static string tagmask_Truncate {
            get {
                return ResourceManager.GetString("tagmask_Truncate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个 的本地化字符串。
        /// </summary>
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温度 的本地化字符串。
        /// </summary>
        internal static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 次 的本地化字符串。
        /// </summary>
        internal static string Times {
            get {
                return ResourceManager.GetString("Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 长度必须小于247 (255-7) 的本地化字符串。
        /// </summary>
        internal static string tip6BWriteLenRange {
            get {
                return ResourceManager.GetString("tip6BWriteLenRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 访问密码 的本地化字符串。
        /// </summary>
        internal static string tipAccessPwd {
            get {
                return ResourceManager.GetString("tipAccessPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 访问密码输入有误，请输入十六进制字符串，eg: 11 22 33 44 的本地化字符串。
        /// </summary>
        internal static string tipAccessPwdCheck {
            get {
                return ResourceManager.GetString("tipAccessPwdCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经锁定 的本地化字符串。
        /// </summary>
        internal static string tipAlreadyLocked {
            get {
                return ResourceManager.GetString("tipAlreadyLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天线组 的本地化字符串。
        /// </summary>
        internal static string tipAntGroup {
            get {
                return ResourceManager.GetString("tipAntGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择至少一个天线至少轮询一次，并重复至少一次。 的本地化字符串。
        /// </summary>
        internal static string tipAtLeastOneAntennaAndStayAtLeastOnce {
            get {
                return ResourceManager.GetString("tipAtLeastOneAntennaAndStayAtLeastOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BlockWrite 的本地化字符串。
        /// </summary>
        internal static string tipBlockWrite {
            get {
                return ResourceManager.GetString("tipBlockWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入范围在[0, 255]的值 的本地化字符串。
        /// </summary>
        internal static string tipByteCheck {
            get {
                return ResourceManager.GetString("tipByteCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能锁定 的本地化字符串。
        /// </summary>
        internal static string tipCannotLocked {
            get {
                return ResourceManager.GetString("tipCannotLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 勾选后，已盘标签总个数实际上是本轮盘存的去重标签总个数，与保存的统计信息一致 的本地化字符串。
        /// </summary>
        internal static string tipCheckBoxSaveLog {
            get {
                return ResourceManager.GetString("tipCheckBoxSaveLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除 的本地化字符串。
        /// </summary>
        internal static string tipClear {
            get {
                return ResourceManager.GetString("tipClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除过滤 的本地化字符串。
        /// </summary>
        internal static string tipClearTagMask {
            get {
                return ResourceManager.GetString("tipClearTagMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接读写器 的本地化字符串。
        /// </summary>
        internal static string tipConnect {
            get {
                return ResourceManager.GetString("tipConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接失败，原因是 的本地化字符串。
        /// </summary>
        internal static string tipConnectFailedCause {
            get {
                return ResourceManager.GetString("tipConnectFailedCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义Session和Target盘存 的本地化字符串。
        /// </summary>
        internal static string tipCustomizeTargetSessionInventory {
            get {
                return ResourceManager.GetString("tipCustomizeTargetSessionInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出成功 的本地化字符串。
        /// </summary>
        internal static string tipDataExportSuccess {
            get {
                return ResourceManager.GetString("tipDataExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请至少输入8个字节 的本地化字符串。
        /// </summary>
        internal static string tipEightBytesAtLeast {
            get {
                return ResourceManager.GetString("tipEightBytesAtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不允许空的字符串 的本地化字符串。
        /// </summary>
        internal static string tipEmptyString {
            get {
                return ResourceManager.GetString("tipEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使能温感标签JH1 的本地化字符串。
        /// </summary>
        internal static string tipEnableJohar_1 {
            get {
                return ResourceManager.GetString("tipEnableJohar_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定这个地址有永久的写保护吗? 的本地化字符串。
        /// </summary>
        internal static string tipEnsurePermanentLock {
            get {
                return ResourceManager.GetString("tipEnsurePermanentLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常 的本地化字符串。
        /// </summary>
        internal static string tipError {
            get {
                return ResourceManager.GetString("tipError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行成功 的本地化字符串。
        /// </summary>
        internal static string tipExecSuccess {
            get {
                return ResourceManager.GetString("tipExecSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行次数 的本地化字符串。
        /// </summary>
        internal static string tipExecuteTime {
            get {
                return ResourceManager.GetString("tipExecuteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败，原因是 的本地化字符串。
        /// </summary>
        internal static string tipFailedCause {
            get {
                return ResourceManager.GetString("tipFailedCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快速盘存 的本地化字符串。
        /// </summary>
        internal static string tipFastInventory {
            get {
                return ResourceManager.GetString("tipFastInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快速盘存 的本地化字符串。
        /// </summary>
        internal static string tipFastSwitch {
            get {
                return ResourceManager.GetString("tipFastSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请至少输入4个字节 的本地化字符串。
        /// </summary>
        internal static string tipFourBytesAtLeast {
            get {
                return ResourceManager.GetString("tipFourBytesAtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 频谱范围不符合规范，请参照通信协议 的本地化字符串。
        /// </summary>
        internal static string tipFreqNotInRegion {
            get {
                return ResourceManager.GetString("tipFreqNotInRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取选定的标签 的本地化字符串。
        /// </summary>
        internal static string tipGetAccessEpcMatch {
            get {
                return ResourceManager.GetString("tipGetAccessEpcMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取并清空缓存 的本地化字符串。
        /// </summary>
        internal static string tipGetAndResetInventoryBuffer {
            get {
                return ResourceManager.GetString("tipGetAndResetInventoryBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取天线检测 的本地化字符串。
        /// </summary>
        internal static string tipGetAntDetector {
            get {
                return ResourceManager.GetString("tipGetAntDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取DRM模式 的本地化字符串。
        /// </summary>
        internal static string tipGetDrmMode {
            get {
                return ResourceManager.GetString("tipGetDrmMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取版本 的本地化字符串。
        /// </summary>
        internal static string tipGetFirmwareVersion {
            get {
                return ResourceManager.GetString("tipGetFirmwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取射频规范 的本地化字符串。
        /// </summary>
        internal static string tipGetFrequencyRegion {
            get {
                return ResourceManager.GetString("tipGetFrequencyRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取匹配阻抗 的本地化字符串。
        /// </summary>
        internal static string tipGetImpedanceMatch {
            get {
                return ResourceManager.GetString("tipGetImpedanceMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取内部版本 的本地化字符串。
        /// </summary>
        internal static string tipGetInternalVersion {
            get {
                return ResourceManager.GetString("tipGetInternalVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取缓存 的本地化字符串。
        /// </summary>
        internal static string tipGetInventoryBuffer {
            get {
                return ResourceManager.GetString("tipGetInventoryBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取缓存标签个数 的本地化字符串。
        /// </summary>
        internal static string tipGetInventoryBufferTagCount {
            get {
                return ResourceManager.GetString("tipGetInventoryBufferTagCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取Impinj Monza快速读TID功能 的本地化字符串。
        /// </summary>
        internal static string tipGetMonzaStatus {
            get {
                return ResourceManager.GetString("tipGetMonzaStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取NetPort配置成功 的本地化字符串。
        /// </summary>
        internal static string tipGetNetPortSucess {
            get {
                return ResourceManager.GetString("tipGetNetPortSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取输出功率 的本地化字符串。
        /// </summary>
        internal static string tipGetOutputPower {
            get {
                return ResourceManager.GetString("tipGetOutputPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取射频通讯链路配置 的本地化字符串。
        /// </summary>
        internal static string tipGetProfile {
            get {
                return ResourceManager.GetString("tipGetProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取当前天线组 的本地化字符串。
        /// </summary>
        internal static string tipGetReaderAntGroup {
            get {
                return ResourceManager.GetString("tipGetReaderAntGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取读写器识别标记 的本地化字符串。
        /// </summary>
        internal static string tipGetReaderIdentifier {
            get {
                return ResourceManager.GetString("tipGetReaderIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取读写器温度 的本地化字符串。
        /// </summary>
        internal static string tipGetReaderTemperature {
            get {
                return ResourceManager.GetString("tipGetReaderTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取过滤设置 的本地化字符串。
        /// </summary>
        internal static string tipGetTagMask {
            get {
                return ResourceManager.GetString("tipGetTagMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取工作天线 的本地化字符串。
        /// </summary>
        internal static string tipGetWorkAntenna {
            get {
                return ResourceManager.GetString("tipGetWorkAntenna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有匹配 的本地化字符串。
        /// </summary>
        internal static string tipHaveNoMatch {
            get {
                return ResourceManager.GetString("tipHaveNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择一个标签 的本地化字符串。
        /// </summary>
        internal static string tipHaveNotYetSelectedTag {
            get {
                return ResourceManager.GetString("tipHaveNotYetSelectedTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TCP客户端模式，模块KeepAlive，可以检测何时设备断开连接 的本地化字符串。
        /// </summary>
        internal static string tipHeartbeatEn {
            get {
                return ResourceManager.GetString("tipHeartbeatEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用串口协商配置 的本地化字符串。
        /// </summary>
        internal static string tipHwCfgComCfgEn {
            get {
                return ResourceManager.GetString("tipHwCfgComCfgEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dhcp，启用动态分配IP 的本地化字符串。
        /// </summary>
        internal static string tipHwCfgDhcpEn {
            get {
                return ResourceManager.GetString("tipHwCfgDhcpEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非法值 的本地化字符串。
        /// </summary>
        internal static string tipInvalid {
            get {
                return ResourceManager.GetString("tipInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行次数至少1次，负数为无线循环 的本地化字符串。
        /// </summary>
        internal static string tipInvalidExecuteTimes {
            get {
                return ResourceManager.GetString("tipInvalidExecuteTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的参数 的本地化字符串。
        /// </summary>
        internal static string tipInvalidParameter {
            get {
                return ResourceManager.GetString("tipInvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 由于指令发出到收到返回需要耗费时间，请根据指令实际耗时设置这个时间间隔 的本地化字符串。
        /// </summary>
        internal static string tipInvCmdInterval {
            get {
                return ResourceManager.GetString("tipInvCmdInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指令间隔时间 的本地化字符串。
        /// </summary>
        internal static string tipInvCmdIntervalTime {
            get {
                return ResourceManager.GetString("tipInvCmdIntervalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缓存模式盘存 的本地化字符串。
        /// </summary>
        internal static string tipInventory {
            get {
                return ResourceManager.GetString("tipInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 盘存6B标签 的本地化字符串。
        /// </summary>
        internal static string tipInventory6B {
            get {
                return ResourceManager.GetString("tipInventory6B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在盘存6B标签 的本地化字符串。
        /// </summary>
        internal static string tipInventorying6B {
            get {
                return ResourceManager.GetString("tipInventorying6B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实时盘存 的本地化字符串。
        /// </summary>
        internal static string tipInventoryReal {
            get {
                return ResourceManager.GetString("tipInventoryReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -1 无线循环 的本地化字符串。
        /// </summary>
        internal static string tipInvExecTime {
            get {
                return ResourceManager.GetString("tipInvExecTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从Target A开始盘存，参数为Target盘存的次数，如果参数为2，则A-&gt;B-&gt;B-&gt;A-&gt;... 的本地化字符串。
        /// </summary>
        internal static string tipInvReverseTarget {
            get {
                return ResourceManager.GetString("tipInvReverseTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 灭活密码 的本地化字符串。
        /// </summary>
        internal static string tipKillPwd {
            get {
                return ResourceManager.GetString("tipKillPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销毁标签 的本地化字符串。
        /// </summary>
        internal static string tipKillTag {
            get {
                return ResourceManager.GetString("tipKillTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功加载配置文件 的本地化字符串。
        /// </summary>
        internal static string tipLoadCfgSuccess {
            get {
                return ResourceManager.GetString("tipLoadCfgSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁定6B标签 的本地化字符串。
        /// </summary>
        internal static string tipLock6BTag {
            get {
                return ResourceManager.GetString("tipLock6BTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功锁定 的本地化字符串。
        /// </summary>
        internal static string tipLockedSuccess {
            get {
                return ResourceManager.GetString("tipLockedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁定标签 的本地化字符串。
        /// </summary>
        internal static string tipLockTag {
            get {
                return ResourceManager.GetString("tipLockTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须大于一个Word（也就是2 Bytes） 的本地化字符串。
        /// </summary>
        internal static string tipMoreThanOneWord {
            get {
                return ResourceManager.GetString("tipMoreThanOneWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为必选项 的本地化字符串。
        /// </summary>
        internal static string tipMustBeOptions {
            get {
                return ResourceManager.GetString("tipMustBeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总设备数 的本地化字符串。
        /// </summary>
        internal static string tipNetPortDeviceCount {
            get {
                return ResourceManager.GetString("tipNetPortDeviceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NetPort操作超时 的本地化字符串。
        /// </summary>
        internal static string tipNetPortOperationTimeout {
            get {
                return ResourceManager.GetString("tipNetPortOperationTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有选择天线 的本地化字符串。
        /// </summary>
        internal static string tipNoAntennaSelect {
            get {
                return ResourceManager.GetString("tipNoAntennaSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择操作的设备 的本地化字符串。
        /// </summary>
        internal static string tipNoDeviceSelect {
            get {
                return ResourceManager.GetString("tipNoDeviceSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有找到网卡 的本地化字符串。
        /// </summary>
        internal static string tipNoNetCardFound {
            get {
                return ResourceManager.GetString("tipNoNetCardFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有发现过滤设置 的本地化字符串。
        /// </summary>
        internal static string tipNoTagMask {
            get {
                return ResourceManager.GetString("tipNoTagMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不包含键值 的本地化字符串。
        /// </summary>
        internal static string tipNotContainsKey {
            get {
                return ResourceManager.GetString("tipNotContainsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持 的本地化字符串。
        /// </summary>
        internal static string tipNotSupport {
            get {
                return ResourceManager.GetString("tipNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出功率范围是 [0-33] dBm 的本地化字符串。
        /// </summary>
        internal static string tipOutPutPowerRange {
            get {
                return ResourceManager.GetString("tipOutPutPowerRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当网络断开, 关闭Socket连接 的本地化字符串。
        /// </summary>
        internal static string tipPhyDisconnect {
            get {
                return ResourceManager.GetString("tipPhyDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入长度值 的本地化字符串。
        /// </summary>
        internal static string tipPleaseInputLen {
            get {
                return ResourceManager.GetString("tipPleaseInputLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入锁定地址 的本地化字符串。
        /// </summary>
        internal static string tipPleaseInputLockAddr {
            get {
                return ResourceManager.GetString("tipPleaseInputLockAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入查询地址 的本地化字符串。
        /// </summary>
        internal static string tipPleaseInputQueryAddr {
            get {
                return ResourceManager.GetString("tipPleaseInputQueryAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入起始地址 的本地化字符串。
        /// </summary>
        internal static string tipPleaseInputStartAddr {
            get {
                return ResourceManager.GetString("tipPleaseInputStartAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先输入UID 的本地化字符串。
        /// </summary>
        internal static string tipPleaseInputUID {
            get {
                return ResourceManager.GetString("tipPleaseInputUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询6B标签 的本地化字符串。
        /// </summary>
        internal static string tipQuery6BTag {
            get {
                return ResourceManager.GetString("tipQuery6BTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在tcp客户端模式中使用随机本地端口 的本地化字符串。
        /// </summary>
        internal static string tipRandEn {
            get {
                return ResourceManager.GetString("tipRandEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取6B标签 的本地化字符串。
        /// </summary>
        internal static string tipRead6BTag {
            get {
                return ResourceManager.GetString("tipRead6BTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取Gpio的值 的本地化字符串。
        /// </summary>
        internal static string tipReadGpioValue {
            get {
                return ResourceManager.GetString("tipReadGpioValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取传感器标签 的本地化字符串。
        /// </summary>
        internal static string tipReadSensorTag {
            get {
                return ResourceManager.GetString("tipReadSensorTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读标签 的本地化字符串。
        /// </summary>
        internal static string tipReadTag {
            get {
                return ResourceManager.GetString("tipReadTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取多个区域 的本地化字符串。
        /// </summary>
        internal static string tipReadTagMultiBank {
            get {
                return ResourceManager.GetString("tipReadTagMultiBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reconnect Success 的本地化字符串。
        /// </summary>
        internal static string tipReconnectSuccess {
            get {
                return ResourceManager.GetString("tipReconnectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当网络连接，清除串口数据 的本地化字符串。
        /// </summary>
        internal static string tipResetCtrl {
            get {
                return ResourceManager.GetString("tipResetCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空缓存 的本地化字符串。
        /// </summary>
        internal static string tipResetInventoryBuffer {
            get {
                return ResourceManager.GetString("tipResetInventoryBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置Cfg成功，请重新NetPort并获取更新的结果 的本地化字符串。
        /// </summary>
        internal static string tipResetNetPortSucess {
            get {
                return ResourceManager.GetString("tipResetNetPortSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置读写器 的本地化字符串。
        /// </summary>
        internal static string tipResetReader {
            get {
                return ResourceManager.GetString("tipResetReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择一个文件来保存传输层日志记录 的本地化字符串。
        /// </summary>
        internal static string tipSaveLog {
            get {
                return ResourceManager.GetString("tipSaveLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存配置文件 的本地化字符串。
        /// </summary>
        internal static string tipSaveNetPortCfgFile {
            get {
                return ResourceManager.GetString("tipSaveNetPortCfgFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NetPort配置设置或者恢复默认成功 的本地化字符串。
        /// </summary>
        internal static string tipSaveOrDefaultNetPortSucess {
            get {
                return ResourceManager.GetString("tipSaveOrDefaultNetPortSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected温感标签JH1 的本地化字符串。
        /// </summary>
        internal static string tipSelectedJohar_1 {
            get {
                return ResourceManager.GetString("tipSelectedJohar_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择要锁定的区域 的本地化字符串。
        /// </summary>
        internal static string tipSelectLockBank {
            get {
                return ResourceManager.GetString("tipSelectLockBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择锁定类型 的本地化字符串。
        /// </summary>
        internal static string tipSelectLockType {
            get {
                return ResourceManager.GetString("tipSelectLockType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择操作区域 的本地化字符串。
        /// </summary>
        internal static string tipSelectMemBank {
            get {
                return ResourceManager.GetString("tipSelectMemBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择要加载的配置文件 的本地化字符串。
        /// </summary>
        internal static string tipSelectNetPortCfgFile {
            get {
                return ResourceManager.GetString("tipSelectNetPortCfgFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string tipSet {
            get {
                return ResourceManager.GetString("tipSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置选定标签 的本地化字符串。
        /// </summary>
        internal static string tipSetAccessEpcMatch {
            get {
                return ResourceManager.GetString("tipSetAccessEpcMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置天线连接检测阈值 的本地化字符串。
        /// </summary>
        internal static string tipSetAntDetector {
            get {
                return ResourceManager.GetString("tipSetAntDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置蜂鸣器 的本地化字符串。
        /// </summary>
        internal static string tipSetBeeperMode {
            get {
                return ResourceManager.GetString("tipSetBeeperMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置射频规范 的本地化字符串。
        /// </summary>
        internal static string tipSetFrequencyRegion {
            get {
                return ResourceManager.GetString("tipSetFrequencyRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置匹配阻抗 的本地化字符串。
        /// </summary>
        internal static string tipSetImpedanceMatch {
            get {
                return ResourceManager.GetString("tipSetImpedanceMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置Impinj Monza快速读TID功能 的本地化字符串。
        /// </summary>
        internal static string tipSetMonzaStatus {
            get {
                return ResourceManager.GetString("tipSetMonzaStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置输出功率 的本地化字符串。
        /// </summary>
        internal static string tipSetOutputPower {
            get {
                return ResourceManager.GetString("tipSetOutputPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置射频通讯链路配置 的本地化字符串。
        /// </summary>
        internal static string tipSetProfile {
            get {
                return ResourceManager.GetString("tipSetProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置读写器地址 的本地化字符串。
        /// </summary>
        internal static string tipSetReadAddress {
            get {
                return ResourceManager.GetString("tipSetReadAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置当前工作天线组 的本地化字符串。
        /// </summary>
        internal static string tipSetReaderAntGroup {
            get {
                return ResourceManager.GetString("tipSetReaderAntGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置读写器识别标记 的本地化字符串。
        /// </summary>
        internal static string tipSetReaderIdentifier {
            get {
                return ResourceManager.GetString("tipSetReaderIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置过滤设置 的本地化字符串。
        /// </summary>
        internal static string tipSetTagMask {
            get {
                return ResourceManager.GetString("tipSetTagMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置临时功率 的本地化字符串。
        /// </summary>
        internal static string tipSetTempOutpower {
            get {
                return ResourceManager.GetString("tipSetTempOutpower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置模块串口波特率 的本地化字符串。
        /// </summary>
        internal static string tipSetUartBaudrate {
            get {
                return ResourceManager.GetString("tipSetUartBaudrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置工作天线 的本地化字符串。
        /// </summary>
        internal static string tipSetWorkAntenna {
            get {
                return ResourceManager.GetString("tipSetWorkAntenna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 耗时 的本地化字符串。
        /// </summary>
        internal static string tipSpendTime {
            get {
                return ResourceManager.GetString("tipSpendTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始 的本地化字符串。
        /// </summary>
        internal static string tipStart {
            get {
                return ResourceManager.GetString("tipStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止盘存 的本地化字符串。
        /// </summary>
        internal static string tipStopInventory {
            get {
                return ResourceManager.GetString("tipStopInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功保存配置文件 的本地化字符串。
        /// </summary>
        internal static string tipStoreCfgToFileSuccess {
            get {
                return ResourceManager.GetString("tipStoreCfgToFileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string tipSuccess {
            get {
                return ResourceManager.GetString("tipSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功写入 的本地化字符串。
        /// </summary>
        internal static string tipSuccessfulWrite {
            get {
                return ResourceManager.GetString("tipSuccessfulWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功保存 的本地化字符串。
        /// </summary>
        internal static string tipSuccessSave {
            get {
                return ResourceManager.GetString("tipSuccessSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用时，使用S1模式inventory，它适用于大多数Impinj标记 的本地化字符串。
        /// </summary>
        internal static string tipTagFocus {
            get {
                return ResourceManager.GetString("tipTagFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过滤设置操作 的本地化字符串。
        /// </summary>
        internal static string tipTagMask {
            get {
                return ResourceManager.GetString("tipTagMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字节已被锁定 的本地化字符串。
        /// </summary>
        internal static string tipThisByteIsAlreadyLocked {
            get {
                return ResourceManager.GetString("tipThisByteIsAlreadyLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这个字节没有被锁定 的本地化字符串。
        /// </summary>
        internal static string tipThisByteIsNotLocked {
            get {
                return ResourceManager.GetString("tipThisByteIsNotLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功锁定该字节 的本地化字符串。
        /// </summary>
        internal static string tipThisByteIsSuccessLocked {
            get {
                return ResourceManager.GetString("tipThisByteIsSuccessLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总读取次数 的本地化字符串。
        /// </summary>
        internal static string tipTotalCount {
            get {
                return ResourceManager.GetString("tipTotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入至少12字节的字符串 的本地化字符串。
        /// </summary>
        internal static string tipTwelveBytesAtLeast {
            get {
                return ResourceManager.GetString("tipTwelveBytesAtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总标签数 的本地化字符串。
        /// </summary>
        internal static string tipUniqueCount {
            get {
                return ResourceManager.GetString("tipUniqueCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知错误 的本地化字符串。
        /// </summary>
        internal static string tipUnknowError {
            get {
                return ResourceManager.GetString("tipUnknowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UnSelected温感标签JH1 的本地化字符串。
        /// </summary>
        internal static string tipUnSelectedJohar_1 {
            get {
                return ResourceManager.GetString("tipUnSelectedJohar_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有加载文件 的本地化字符串。
        /// </summary>
        internal static string tipWithoutLoadAnyFile {
            get {
                return ResourceManager.GetString("tipWithoutLoadAnyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有选择文件 的本地化字符串。
        /// </summary>
        internal static string tipWithoutSelectAnyFile {
            get {
                return ResourceManager.GetString("tipWithoutSelectAnyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写6B标签 的本地化字符串。
        /// </summary>
        internal static string tipWrite6BTag {
            get {
                return ResourceManager.GetString("tipWrite6BTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置Gpio的值 的本地化字符串。
        /// </summary>
        internal static string tipWriteGpioValue {
            get {
                return ResourceManager.GetString("tipWriteGpioValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写标签 的本地化字符串。
        /// </summary>
        internal static string tipWriteTag {
            get {
                return ResourceManager.GetString("tipWriteTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recv 的本地化字符串。
        /// </summary>
        internal static string TransportRecv {
            get {
                return ResourceManager.GetString("TransportRecv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send 的本地化字符串。
        /// </summary>
        internal static string TransportSend {
            get {
                return ResourceManager.GetString("TransportSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP地址格式错误，例如: 192.168.0.178 的本地化字符串。
        /// </summary>
        internal static string tWrongIpAddr {
            get {
                return ResourceManager.GetString("tWrongIpAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mac地址格式错误，例如: 12:34:56:AB:CD:EF 的本地化字符串。
        /// </summary>
        internal static string tWrongMacAddr {
            get {
                return ResourceManager.GetString("tWrongMacAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 临时功率 的本地化字符串。
        /// </summary>
        internal static string useCmd8A25 {
            get {
                return ResourceManager.GetString("useCmd8A25", resourceCulture);
            }
        }
    }
}
